// <auto-generated />
namespace Sanita.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AgregadoBannerNombre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregadoBannerNombre));
        
        string IMigrationMetadata.Id
        {
            get { return "201410201415157_Agregado-Banner.Nombre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
